language: python
python:
  - '2.7'
before_install:
  - npm cache clean
  - gem install compass
  - npm install -g gulp
install:
  - npm install
  - gulp
before_script:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.19.zip -nv
  - unzip -q google_appengine_1.9.19.zip
script: 
  - return 0
after_script:
  - cd google_appengine && python appcfg.py --oauth2_refresh_token=$GAE_OAUTH_TOKEN update ../dist
  - return 0
notifications:
  email: false
branches:
  only:
    - master
env:
  global:
    secure: NgqZEEbuL1sNOKF7xMIkzLG7MDlfiWIH2XcY6UtUtfXdeQ4K3ZFvvwVbwPVVqXL6FAKIoGl15uUzH5GX9lpoucScy5pQR0ItHiFzbrNlzFN437ycOoWF+mmtfI5EYOb5nZdlQHEwyrhxa6UhAGTJATOiC9dR8zzWqh589vI3b6E=
