application: on-site-auto
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: static_pages/index.html
  upload: static_pages/index.html
  
- url: /index.html
  static_files: static_pages/index.html
  upload: static_pages/index.html
  
- url: /about.html
  static_files: static_pages/about.html
  upload: static_pages/about.html
 
- url: /contact.html
  static_files: static_pages/contact.html
  upload: static_pages/contact.html
  
- url: /desertmountainfab.html
  static_files: static_pages/desertmountainfab.html
  upload: static_pages/desertmountainfab.html
  
- url: /reviews.html
  static_files: static_pages/reviews.html
  upload: static_pages/reviews.html
  
- url: /(.*.(txt|xml))
  static_files: static_pages/\1
  upload: static_pages/(.*.(txt|xml))
  
- url: /(.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff))
  static_files: static_pages/\1
  upload: static_pages/(.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff))


libraries:
- name: webapp2
  version: "2.5.2"
