application: on-site-auto
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html
  
- url: /index.html
  static_files: index.html
  upload: index.html
  
- url: /about.html
  static_files: about.html
  upload: about.html
 
- url: /contact.html
  static_files: contact.html
  upload: contact.html
  
- url: /desertmountainfab.html
  static_files: desertmountainfab.html
  upload: desertmountainfab.html
  
- url: /testimonials.html
  static_files: testimonials.html
  upload: testimonials.html
  
- url: /(.*.(txt|xml))
  static_files: \1
  upload: (.*.(txt|xml))
  
- url: /(.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff|js))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff|js))


libraries:
- name: webapp2
  version: "2.5.2"
